language: "es"

machine_settings:
  play_cost: 1
  coin_value_for_jackpot: 50.0
  spin_duration:
    base_ticks: 60
    reel_delay_ticks: 20
    extra_random_ticks: 20
    timeout_seconds: 15

jackpot:
  enabled: true
  starting_amount: 500.0

purchase_discounts:
  vip1:
    permission: "slotmachine.discount.vip1"
    percentage: 10
  vip2:
    permission: "slotmachine.discount.vip2"
    percentage: 25

sounds:
  spin: "BLOCK_NOTE_BLOCK_PLING"
  win: "ENTITY_PLAYER_LEVELUP"
  lose: "ENTITY_VILLAGER_NO"
  coin_insert: "ENTITY_ITEM_PICKUP"
  jackpot_win: "UI_TOAST_CHALLENGE_COMPLETE"
  gui_click: "UI_BUTTON_CLICK"

roulette_items:
  CHERRY_SAPLING: 60
  COAL: 50
  REDSTONE: 40
  LAPIS_LAZULI: 35
  IRON_INGOT: 25
  GOLD_INGOT: 15
  EMERALD: 8
  DIAMOND: 3

prizes:
  jackpot_emerald:
    reward: 5000.0
  gold_win:
    reward: 1000.0
  iron_win:
    reward: 500.0
  two_diamonds:
    reward: 250.0
  two_emeralds:
    reward: 100.0